# no-finetune(stage one), no mlp, VASE
# vgg16/Davenet
# base+tri
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
# base+tri+cc, VASE
#CUDA_VISIBLE_DEVICES=6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth0.8 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth1.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth1.5 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=7 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth2.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth4.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth4.5 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=7 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.2 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.3 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.4 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.5 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.6 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.7 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth6.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth8.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth9.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth10.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth12.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type vgg16

# resnet50/ResDAVEnet
# base+tri
#CUDA_VISIBLE_DEVICES=6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_resnet50_vse_base --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type resnet50
# base+tri+cc, VASE
#CUDA_VISIBLE_DEVICES=6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_resnet50_vse_base_2rec_l2norm_smooth4.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type resnet50
#CUDA_VISIBLE_DEVICES=7 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_resnet50_vse_base_2rec_l2norm_smooth6.0 --num_epochs 100 --batch_size 32 --num_streams 3 --learning_rate 0.0002 --cnn_type resnet50





# finetune(stage two), no mlp, VASE
# vgg16/DAVEnet
# base+tri
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
# base+tri+cc, VASE
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth0.8 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth0.8/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5,7 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth1.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth1.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5,7 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth1.5 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth1.5/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=7,6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth2.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth2.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=7,6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth4.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth4.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=7 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth4.5 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth4.5/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=7 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.2 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.2/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.3 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.3/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=7 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.4 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.4/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.5 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.5/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.6 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.6/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.7 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth5.7/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth6.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth6.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth8.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth8.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=6 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth9.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth9.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=4 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth10.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth10.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16
#CUDA_VISIBLE_DEVICES=7 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth12.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_vgg16_vse_base_2rec_l2norm_smooth12.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type vgg16

# resnet50/ResDAVEnet
# base+tri
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_resnet50_vse_base --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_resnet50_vse_base/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type resnet50
# base+tri+cc, VASE
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_resnet50_vse_base_2rec_l2norm_smooth4.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_resnet50_vse_base_2rec_l2norm_smooth4.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type resnet50
#CUDA_VISIBLE_DEVICES=5 python train_f8k.py --data_path data/ --data_name f8k --logger_name runs/f8k_finetune_three_streams_bs_32_Bi_GRU_nol2norm2_resnet50_vse_base_2rec_l2norm_smooth6.0 --resume runs/f8k_three_streams_bs_32_Bi_GRU_nol2norm2_resnet50_vse_base_2rec_l2norm_smooth6.0/model_best.pth.tar --num_epochs 100 --batch_size 32 --num_streams 3 --finetune --learning_rate 0.00002 --cnn_type resnet50
